insert into Gebruiker values (1, 'van der Geer', 'Java', false, 'HANDELAAR','corne','Corne','12345','apeldoorn');
insert into Gebruiker values (2, 'Crombach', 'Java', false, 'HANDELAAR','leon','Leon','12345','zutphen');
insert into Gebruiker values (3, 'Janssen', 'Kotlin', false, 'HANDELAAR','bram','Bram','42','geenidee');
insert into `Gebruiker Bezorgwijzes` values (1, 'THUISAFHALEN');
insert into `Gebruiker Bezorgwijzes` values (2, 'THUISAFHALEN');
insert into `Gebruiker Bezorgwijzes` values (2, 'VERSTUREN');
insert into `Gebruiker Bezorgwijzes` values (3, 'THUISAFHALEN');
insert into `Gebruiker Bezorgwijzes` values (3, 'VERSTUREN');
insert into `Gebruiker Bezorgwijzes` values (3, 'MAGAZIJNBELASTINGDIENST');
insert into Advertentie values (1, 'THUISAFHALEN', 'PRODUCT','een mooie fiets om mee te fietsen.', 100.00, 'BESCHIKBAAR', 'mooie fiets', 1);
insert into Advertentie values (2, null, 'DIENST','ik bied mezelf aan als DM voor D&D.', 75.99, 'BESCHIKBAAR', 'GM voor D&D', 2);
insert into Advertentie values (3, 'VERSTUREN', 'PRODUCT','echte sneeuw van de noordpool.', 99.34, 'BESCHIKBAAR', 'sneeuw', 2);
insert into Advertentie values (4, null, 'DIENST','ik bied privé lesjes aan voor je OCP, nu voor een vriendenprijsje.', 500.00, 'BESCHIKBAAR', 'privé-les OCP', 3);
insert into Advertentie values (5, 'MAGAZIJNDEPOT', 'PRODUCT','Hij doet het nog prima, APK tot 16 mei 2023', 50.00, 'BESCHIKBAAR', 'prima auto', 3);
